export const SUPPORTED_LANGUAGES = [
    {code: 'hi-IN', name: 'Hindi', native: 'हिंदी'},
    {code: 'gu-IN', name: 'Gujarati', native: 'ગુજરાતી'},
    {code: 'mr-IN', name: 'Marathi', native: 'मराठी'},
    {code: 'bn-IN', name: 'Bengali', native: 'বাংলা'},
    {code: 'ta-IN', name: 'Tamil', native: 'தமிழ்'},
    {code: 'te-IN', name: 'Telugu', native: 'తెలుగు'},
    {code: 'kn-IN', name: 'Kannada', native: 'ಕನ್ನಡ'},
    {code: 'ml-IN', name: 'Malayalam', native: 'മലയാളം'},
    {code: 'pa-IN', name: 'Punjabi', native: 'ਪੰਜਾਬੀ'},
    {code: 'od-IN', name: 'Odia', native: 'ଓଡ଼ିଆ'},
    {code: 'as-IN', name: 'Assamese', native: 'অসমীয়া'},
    {code: 'ur-IN', name: 'Urdu', native: 'اردو'},
    {code: 'ne-IN', name: 'Nepali', native: 'नेपाली'},
    {code: 'kok-IN', name: 'Konkani', native: 'कोंकणी'},
    {code: 'ks-IN', name: 'Kashmiri', native: 'कश्मीरी'},
    {code: 'sd-IN', name: 'Sindhi', native: 'सिंधी'},
    {code: 'sa-IN', name: 'Sanskrit', native: 'संस्कृतम्'},
    {code: 'sat-IN', name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ'},
    {code: 'mni-IN', name: 'Manipuri', native: 'ꯃꯤꯇꯩꯂꯣꯟ'},
    {code: 'brx-IN', name: 'Bodo', native: 'बर'},
    {code: 'mai-IN', name: 'Maithili', native: 'मैथिली'},
    {code: 'doi-IN', name: 'Dogri', native: 'डोगरी'},
];